name: tags
on:
  push:
    tags:
      - 'curl'
jobs:
  curl:
    runs-on: ubuntu-latest
    steps:   
      - name: build docker image
        uses: the-actions-org/workflow-dispatch@3133c5d135c7dbe4be4f9793872b6ef331b53bc7
        with:
          workflow: docker.yml
          token: "${{ secrets.REPOSITORY_TOKEN }}"
          inputs: '{ "release":"false", "readme":"false", "run-name":"curl", "etc":{"dockerfile":"curl.dockerfile", "tag":"curl", "version":"8.12.1"} }'