name: tags
on:
  push:
    tags:
      - 'dnslookup'
jobs:
  dnslookup:
    runs-on: ubuntu-latest
    steps:   
      - name: build docker image
        uses: the-actions-org/workflow-dispatch@3133c5d135c7dbe4be4f9793872b6ef331b53bc7
        with:
          workflow: docker.yml
          token: "${{ secrets.REPOSITORY_TOKEN }}"
          inputs: '{ "release":"false", "readme":"false", "run-name":"dnslookup", "etc":{"dockerfile":"dnslookup.dockerfile", "tag":"dnslookup", "version":"1.11.1"} }'