name: node
on:
  workflow_dispatch:
  schedule:
    - cron: "0 5 * * *"
  push:
    tags:
      - 'node'
jobs:
  node:
    runs-on: ubuntu-latest
    steps:
      - name: cron-update / get latest version
        run: |
          LATEST_VERSION=$(curl -s https://api.github.com/repos/nodejs/node/releases/latest | jq -r '.tag_name' | sed 's/v//')
          
          if [ "${LATEST_VERSION}" != "null" ]; then
            if curl -kILs --fail https://hub.docker.com/v2/repositories/11notes/distroless/tags/node-${LATEST_VERSION}; then
              echo "tag ${LATEST_VERSION} exists already!"
            else
              echo "WORKFLOW_AUTO_UPDATE=true" >> "${GITHUB_ENV}"
              echo "LATEST_VERSION=${LATEST_VERSION}" >> "${GITHUB_ENV}"
            fi
          else
            echo "tag ${LATEST_VERSION} is null!"
          fi

      - name: init / base64 nested json
        if: env.WORKFLOW_AUTO_UPDATE == 'true'
        uses: actions/github-script@62c3794a3eb6788d9a2a72b219504732c0c9a298
        with:
          script: |
            const { Buffer } = require('node:buffer');
            const etc = {
              dockerfile:"node.dockerfile",
              tag:"node",
              version:"${{ env.LATEST_VERSION }}",
              arch:"'linux/amd64,linux/arm64'",
            };
            core.exportVariable('WORKFLOW_BASE64JSON', Buffer.from(JSON.stringify(etc)).toString('base64'));

      - name: build docker image
        if: env.WORKFLOW_AUTO_UPDATE == 'true'
        uses: the-actions-org/workflow-dispatch@3133c5d135c7dbe4be4f9793872b6ef331b53bc7
        with:
          wait-for-completion-timeout: "10h"
          workflow: docker.yml
          token: "${{ secrets.REPOSITORY_TOKEN }}"
          inputs: '{ "runs-on":"self-hosted", "release":"false", "readme":"false", "run-name":"node", "etc":"${{ env.WORKFLOW_BASE64JSON }}" }'



      - name: cron-update / get stable version
        run: |
          STABLE_VERSION=$(curl -sSL https://nodejs.org/en/download | grep -oE 'v[0-9]+.[0-9]+.[0-9]+ \(LTS\)' | sed -E 's/v(\d+.\d+.\d+) \(LTS\)/\1/')
          
          if [ "${STABLE_VERSION}" != "null" ]; then
            if curl -kILs --fail https://hub.docker.com/v2/repositories/11notes/distroless/tags/node-${STABLE_VERSION}-stable; then
              echo "tag ${STABLE_VERSION} exists already!"
            else
              echo "WORKFLOW_AUTO_UPDATE_STABLE=true" >> "${GITHUB_ENV}"
              echo "STABLE_VERSION=${STABLE_VERSION}" >> "${GITHUB_ENV}"
            fi
          else
            echo "tag ${STABLE_VERSION} is null!"
          fi

      - name: init / base64 nested json
        if: env.WORKFLOW_AUTO_UPDATE_STABLE == 'true'
        uses: actions/github-script@62c3794a3eb6788d9a2a72b219504732c0c9a298
        with:
          script: |
            const { Buffer } = require('node:buffer');
            const etc = {
              dockerfile:"node.dockerfile",
              tag:"node",
              semversuffix:"stable"
              version:"${{ env.STABLE_VERSION }}",
              arch:"'linux/amd64,linux/arm64'",
            };
            core.exportVariable('WORKFLOW_BASE64JSON_STABLE', Buffer.from(JSON.stringify(etc)).toString('base64'));

      - name: build docker image
        if: env.WORKFLOW_AUTO_UPDATE_STABLE == 'true'
        uses: the-actions-org/workflow-dispatch@3133c5d135c7dbe4be4f9793872b6ef331b53bc7
        with:
          wait-for-completion-timeout: "10h"
          workflow: docker.yml
          token: "${{ secrets.REPOSITORY_TOKEN }}"
          inputs: '{ "runs-on":"self-hosted", "release":"false", "readme":"false", "run-name":"node-stable", "etc":"${{ env.WORKFLOW_BASE64JSON_STABLE }}" }'